### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by rhsu0268** [chadxz/imap-simple#30]
Is it possible for me to get at the the attachments for each individual email rather than to get all attachments from all emails?

**Comment by chadxz** [comment]
You want to be able to get a list of search results, then pull the attachments for each email one at a time, instead of pulling them all at once?

No, that is not possible with the current implementation. You can do that with [node-imap](https://github.com/mscdex/node-imap) though. If you want to make a change to this library to support that, one way I could think to do it would be to expose a new method that allows you to perform a fetch on a uid without a search. This would allow you to use the normal `search()` to retrieve the minimal details for the search you are performing, then do a followup `fetch()` to get extended details on the uids you want.

**Comment by melitus** [comment]
I think you can do that if you specify in your search criteria the subject of the mail you want to download only their attachment
