### ISSUE TITLE
Issue when missing connection

### ISSUE THREAD

**Issue by Adibla** [chadxz/imap-simple#65]
Hi, I've an issue. I tried to do some tests and I saw that if I establish the connection with my imap server and I disconnect my computer from the internet connection and then I reconnect to it, the library seems blocked, and no one Promise.catch are triggered. I don't find the problem and I've no idea how to catch it. Thank you.

**Comment by k2s** [comment]
My findings:
* this issue is related to the underlying project https://github.com/mscdex/node-imap
* `socketTimeout` defaults to 0 and will timeout depending on OS or never
  * if you set it to value different then 0 you need to subscribe to `error` event otherwise it will kill your process
  * I didn't found it useful to change `socketTimeout`
* it is possible to check for connect.status and not call methods if connection was broken
* to reconnect you need to subscribe to `close` event and reconnect

this is my current working test

```js
  async connect () {
    const me = this
    try {
      if (!this._c) {
        this._c = await imaps.connect(this.config)
        this.log.info(`IMAP connected to ${this.config.imap.host}`)
        this._c.on('error', err => {
          // THIS IS REQUIRED not to crash the process on socket error
          this.log.error(err)
        })
        this._c.imap.on('close', () => {
          this._c = null
          setTimeout(() => {
            this.log.debug('IMAP reconnecting after error')
            me.connect()
          }, RECONNECT_TIMEOUT)
        })
      }

      await this._c.openBox('INBOX')
      this.log.info('IMAP INBOX opened')
    } catch (ex) {
      this.log.error(ex)
      setTimeout(() => {
        this.log.debug('IMAP initial reconnect')
        me.connect()
      }, RECONNECT_TIMEOUT)
    }
  }
```
